steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/devops-automation-367109', '.']
  id: build-docker-image

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/devops-automation-367109']
  id: push-docker-image-to-container
  timeout: 960s

images:
- gcr.io/devops-automation-367109/reactapptodo
