version: '3'

services:
  calculator:
    build: ./
    container_name: calculator
    restart: always
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine